### ISSUE TITLE
fix `short::open::tests::test_calculate_implied_rate`

### ISSUE THREAD

**Issue by dpaiton** [delvtech/hyperdrive-rs#2]
Repeated runs of the test results in occasional failure.

```
`thread 'short::open::tests::test_calculate_implied_rate' panicked at crates/hyperdrive-math/src/short/open.rs:589:13:
error 107470370462233 exceeds tolerance of 100000000000000
```

**Comment by dpaiton** [comment]
This is difficult to debug until after we fix #3 and #4 because those errors are showing up more frequently than this error. I'm going to mark this as blocked until those are resolved.

**Comment by dpaiton** [comment]
Done: https://github.com/delvtech/hyperdrive-rs/pull/6

**Comment by dpaiton** [comment]
Reopening as it is still failing:
```
---- short::open::tests::test_calculate_implied_rate stdout ----
thread 'short::open::tests::test_calculate_implied_rate' panicked at crates/hyperdrive-math/src/short/open.rs:610:13:
error 144897155659882 exceeds tolerance of 100000000000000
```

**Comment by dpaiton** [comment]
Resolved per @jrhea (maybe https://github.com/delvtech/hyperdrive-rs/pull/89)
